### ISSUE TITLE
Introduce the Mixin class

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-core#18]
Following [recent talks](https://github.com/ckeditor/ckeditor5-design/issues/52), to make the use of mixins more elegant, we should introduce the Mixin class.

The following is a usage example of it:

```js
var EmitterMixin = new Mixin( {
    method1: ...,
    method2: ...
} );

function TargetClass() {}

EmitterMixin.mixin( TargetClass.prototype );
```

The constructor basically accepts the mixin properties and the class exposes a single `mixin()` method to mix such properties in a target.

**Comment by pjasiun** [comment]
I believe that since we started using classes `Mixin` should work like a multiple inheritance:
```
class LivePosition extends mix( Position, EmitterMixin ) {
    // ...
}
```
Based on: https://hacks.mozilla.org/2015/08/es6-in-depth-subclassing/

We could improve the solution a little, so `LivePosition` will be still an instance of `Position` (but not `EmitterMixin`).

What I do not like in the current solution is that the information that the class use the emitter API is at the very end of the file, after methods which use that API.

**Comment by Reinmar** [comment]
I implemented `utils.mix()` (see #147), but I'm not sure that this makes any sense. We were able to move the mixin calls to the top of class declarations, but:

1. Every time we use `utils.mix( null, EmitterMixin )` we're in fact defining an additional class. Previously we were simply extending the defined class prototype, without creating any additional classes.
2. We needed to add the `super()` calls because now we use `extends` even if class does not extend anything (it just mixes in some stuff).

**Comment by pjasiun** [comment]
I like this solution it is far more readable then the previous one. Adding `super()` and base class is not an issue for me, as long as you do not find any performance problems related to it.

**Comment by pjasiun** [comment]
But I do not know why `EmitterMixin` starts with upper case, it is not a class, it should be lower case, like `utils`.

**Comment by scofalik** [comment]
What I don't like about mixins right now that it is super hard to introduce properties, because they act like static properties - they are shared between all objects. You have to make stupid workarounds.

I'd rather have a solution where there is a class-chain created when you have multiple inheritance. I know that everyone hates multiple inheritance and it usually means that something is wrong with code architecture, but I like the concept.

Why Mixins can't be just usual classes?

**Comment by oleq** [comment]
> Why Mixins can't be just usual classes?
Same question here.

**Comment by Reinmar** [comment]
> Why Mixins can't be just usual classes?

I started implementing this, but it wasn't nice. Look at the code which PJ linked: 

```
function copyProperties(target, source) {
    for (let key of Reflect.ownKeys(source)) {
        if (key !== "constructor" && key !== "prototype" && key !== "name") {
            let desc = Object.getOwnPropertyDescriptor(source, key);
            Object.defineProperty(target, key, desc);
        }
    }
}
```

First you need to get all own keys because class properties are not enumerable.`Object.getOwnPropertyNames()` (which we can use) and `Reflect.ownKeys()` (which we cannot yet, although we could polyfill it) returns things we cannot copy (constructor, prototype, etc.) so we need to filter them out. I even had a working solution at some point but then I thought... do we need this at all? So far we didn't.

Anyway, I'm OK with making mixins real classes if you feel it's worth it.

**Comment by scofalik** [comment]
Let's say I have a class `Shape`. Now I want a scalalble, colored `Circle`.
If I wanted to have some messy code and wanted to to do it by hand, I could do:

```javascript
class __circle extends Shape { ... stuff ... }
class __circle2 extends ScalableMixin {}
class Circle extends ColoredMixin {}
```
can't we simulate it in a loop?

If we wanted to write it like this:
```javascript
class Circle extends utils.mix( Shape, ScalalbleMixin, ColoredMixin ) { ... stuff ... }
```

We would unfortunately have to create "empty" class:
```javascript
class __shape extends Shape {}
class __shape2 extends ScalableMixin {}
class __shape3 extends ColoredMixin {}
class Circle extends __shape3 { ... stuff ... }
```

**Comment by scofalik** [comment]
This is of course a naive way of doing this. I am okay with using `Reflect` or any other build-in methods.

**Comment by Reinmar** [comment]
> What I don't like about mixins right now that it is super hard to introduce properties, because they act like static properties - they are shared between all objects. You have to make stupid workarounds.

It's the same with classes – properties need to be created inside the constructor. So we would need to call mixins constructors... doable, but we're getting dangerously close to multiple inheritance. And you cannot have multiple inheritance in JS because the only place in proto chain where you can add one more class is the end of it. So you would need to rewrite entire chain every time you do multiple inheritance.

> I like this solution, it is far more readable then the previous one. Adding super() and base class is not an issue for me, as long as you do not find any performance problems related to it.

We had a bit more F2F discussion and only PJ didn't like the current `utils.extend()` calls kept at the end of files. I'll propose one more PR where this will be kept but with a small improvement – proper descriptors for the created properties.

**Comment by Reinmar** [comment]
OK, yet another attempt in https://github.com/ckeditor/ckeditor5-core/pull/149. It takes symbols and setters/getters into account. This itself is a reason why it's much better that `_.extend()`.
