### ISSUE TITLE
Extend View Element class.

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#256]
View element class is missing multiple methods. The most important are to get classes and styles as collections, because now they are returned only as regular attributes.

We could also check DOM Element API and CKEditor 4 element API to ensure that there is not important methods missing.

**Comment by Reinmar** [comment]
When talking about class list the implementation can follow the native API. But when talking about styles we need to figure out whether we shouldn't implement some style normalization/matching logic. For instance, when a feature tries to convert `font-family` and the incoming data has `font: 12px 'Arial'` style, it would be great if some method was able to extract `font-family` from the existing style. We missed this feature in CKEditor 4 and there were some issue because of that. However, it's not crucial – it's an enhancement that we can predict today, but implement later.

**Comment by szymonkups** [comment]
Starting with classes. Each access to classes should be synchronized with `class` attribute. Should we always operate directly on this attribute, eg. create `hasClass` / `removeClass` methods that parse `class` attribute each time it is called. Maybe we can follow native API and create `ClassList` that will internally store the class list? It will update `class` attribute when it is needed and update itself when `class` attribute is accessed directly?

**Comment by pjasiun** [comment]
I think that `Element` should have private/protected properties: `attributes`, `styles` i `classes` and do not keep styles and classes in the attributes collection. Then, the `getAttribute` and `setAttribute` methods should be smarter and handle `style` and `class` attribute in different way then other attributes.
