### ISSUE TITLE
Get list of enabled/loaded features for editor instance

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-core#28]
This relates to the #27.

I assume that a real use case for editor is to use different bundled versions of the editor.

I would like to check if some editor instance has some crucial feature enabled so I can know from external code to the editor that the editor will behave as I expect.

``` js
SomeBundledEditor.create( document.querySelector( '#editor' ) ).then( ( editor ) => {
    if ( !editor.plugins.has( 'myApi' ) ) {
        throw new Error( 'Editor must have plugin "myApi" enabled to work with MyCode!' );
    }
    // Now I can use `myApi` plugin functionality
} );
```

**Comment by Reinmar** [comment]
It's a bad smell what you're trying to do because you're programming for a specific implementation at the same time pretending that it's going to work without some features.

OTOH, I agree that you may *want* to do this. It's the easiest way many times to achieve some goal. As you told me – we're thinking in a CKE-centric way and I agree that we need to change this  a bit. However, expect us to oppose every time you ask for such features :P.

This ticket requires #27 and #27 must be resolved in such a way that features will be named.

**Comment by jodator** [comment]
@Reinmar no prob ;) The issue is that when I want to give user a freedom to use its own editor build I must somehow check if the editor build passed to other code is OK.

**Comment by Reinmar** [comment]
Since you can retrieve plugins by names, now, I think that this issue is fixed as well. Just remember to define the static `pluginName` property of your plugins.
