### ISSUE TITLE
Document Model

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#33]
Create a document model data structure. It should contains:
 - ~~linear data~~,
 - document tree,
 - main document model class with ~~`applyTransaction`~~`apply` method,
 - ~~transactions~~ operations.

Applying transactions should create or remove linear data and nodes.

**Comment by pjasiun** [comment]
First, we decided to store all data in the tree structure with the linear interface instead of linear data structure with the tree interface.

Now, because of reasons explained in https://github.com/ckeditor/ckeditor5-design/issues/71 we decided to drop linear interface and linear operations and use tree operations instead, so I am restarting branch for this ticket.

**Comment by pjasiun** [comment]
Follow ups for this ticket: #59, #62, #63, #64, #65, #66, #67, #68, #69.

**Comment by pjasiun** [comment]
We decided that the document class needs some more changes:
 - `RootElement` will be introduced as a child of `Element`. `RootElement` will have reference to the `Document` and may have name.
 - `Document` will have `NamedCollection` of `RootElement`s.
 - there will be one `RootElement` for graveyard (according to idea introduced in https://github.com/ckeditor/ckeditor5-design/issues/71#issuecomment-149928916), and one `RootElement` for each top level editable.
 - there will be only one `Document` per editor instance.

Also we decided that operations should encapsulate internal document mechanism, so `Delta`s will use operations, not knowing anything about the graveyard.

**Comment by pjasiun** [comment]
We also decided that there will be `ReInsertOperation` which will be the reverse for the remove operation. It makes sense because:
 - This operation is in fact the move operation from graveyard, the same way remove operation is in fact move to graveyard. It is more semantically correct to have a reinsert instead of move as a reverses for the remove operation.
 - We may need some additional actions in the future if when we put something to and back from the graveyard, so `(Remove|ReInsert)Operation`s will keep this logic,
 - It encapsulate the graveyard logic better, so in the future if we will implement removing in the different way, we could keep current operation.
 - For the user who observe changes on the element it makes sense to have separate events for these three operations. `ReInsert` is something different that insert, because it will insert element which was already initialized before. It is also definitely something different then `Move`. We can not guess how user want to thread it.

**Comment by pjasiun** [comment]
Also root of the graveyard will be stored in the map of RootElements, the key will be a `Symbol` to avoid conflicts.

**Comment by pjasiun** [comment]
Also https://github.com/ckeditor/ckeditor5-design/wiki/Document-Model needs to be updated.

**Comment by pjasiun** [comment]
One more follow-up: #73.

@scofalik made his review and changed the code according to decisions mentioned above. Then I checked his changes. Now the ticket is ready for the final review and merging into the master branch.

**Comment by Reinmar** [comment]
For the future reference – the PR is in #70.

**Comment by Reinmar** [comment]
1. Expose `sort()` from attrubute's constructor (for both – memory and testability reasons). (I know there's a plan to refactor this bit)
1. Explain what `sort()` actually does. Not what it does not do.
1. `MoveOperation.constructor`'s order of args is weird. `source, numberOfNodes, target` would make more sense.
1. General advice regarding throwing errors - I don't think it makes much sense to specify in the additional error data the context like "this operation". If you have an error, you either know why it may be thrown or you may check this by using debugger. It should be a helper not a debugging tool. I cleaned many errors to contain minimum number of information.
1. I would propose that we always use singular nouns for the namespace fragments. So no `document.operations`, but `document.operation`. (DONE)
1. Current attrs list is very weird. Map or object would make more sense. (I know there's a ticket for that)
1. `Node#positionInParent -> Node#index/getIndex()`. Plus it should rather throw when not found itself in its parent rather than returning `-1` :D.
1. `Node#depth` – I'm not sure it's a good name, but I don't have a better idea :D.
1. Node - the class properties should be sorted. First getters/setters, then public methods, then private methods. (DONE)
1. Why `Node.getPath()`, when `node.depth`? (see https://github.com/ckeditor/ckeditor5-design/issues/88)

Of course none of these is a blocker so you can merge the branch to `master` after checking my changes. I've made quite a lot of them, mainly in the docs.

**Comment by pjasiun** [comment]
> Expose sort() from attrubute's constructor (for both – memory and testability reasons). (I know there's a plan to refactor this bit)
> Explain what sort() actually does. Not what it does not do.

This part of code will be most probably removed in https://github.com/ckeditor/ckeditor5-core/issues/63.

> MoveOperation.constructor's order of args is weird. source, numberOfNodes, target would make more sense.

See #73.

> General advice regarding throwing errors - I don't think it makes much sense to specify in the additional error data the context like "this operation". If you have an error, you either know why it may be thrown or you may check this by using debugger. It should be a helper not a debugging tool. I cleaned many errors to contain minimum number of information.

I see it's done.

> Current attrs list is very weird. Map or object would make more sense. (I know there's a ticket for that)

See https://github.com/ckeditor/ckeditor5-core/issues/63.

> Node#positionInParent -> Node#index/getIndex(). Plus it should rather throw when not found itself in its parent rather than returning -1 :D.

Changed.

> Why Node.getPath(), when node.depth? (see ckeditor/ckeditor5-design#88)

It's confusing for me too. Lets change it when we will have a rule when we use getters and when methods.

**Comment by pjasiun** [comment]
And one more follow-up: https://github.com/ckeditor/ckeditor5-core/issues/76.
