### ISSUE TITLE
OT for operations

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#59]
It should be possible to transform one operation with another. To do it:
 - `Operation.transform( anotherOperation, anotherMoreImportant )` - method should be implemented for all types of operations, where `anotherOperation` is operation to transform with and `anotherMoreImportant` is boolean to determine which operation should we use in case of conflicts,
 - `NoOperation` class should be introduced, for operations which do nothing,
 - existing operation classes should be changed, if needed, most likely move and remove will not need to have nodes,
 - `Operation.reverseOperation()` method should be changed, if needed.

After this ticket it should be possible to combine two sets of operations and undo any operation from the history, still manually working with operations, without a mechanism for handling operation collections.

**Comment by scofalik** [comment]
* I propose `transformBy` or `transformAgainst` or even `getTransformedBy` name for the method. I know it is more typing but it is more clear and descriptive what the method does. Also, to make it clear, the method should return a new instance because transformed operation might even be of a different type, which means other class.
* Yes. Right now, for OT purposes, this class should have `address`, `offset` and `howMany` properties. It may happen that we won't need them in the end, but right now I use those in operations combining algorithm.
* What do you mean by this?

**Comment by pjasiun** [comment]
If like your meaningful names: `getTransformedBy`, `howMany`.`reverseOperation` could also be renamed to `getReversed`.

> What do you mean by this?

That the method which was introduced in #33 may need some changes.

**Comment by pjasiun** [comment]
During the talk we decided that change operation will use single multilevel range.

**Comment by Reinmar** [comment]
Congrats. 4kSLOC just landed on master.
