### ISSUE TITLE
Change data type returned by filter() in Collection and NamedCollection

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-core#71]
Just like `Array.filter()` returns an instance of `Array`, semantically:
* `Collection.filter()` should return a `Collection` instance.
* `NamedCollection.filter()` should return a `NamedCollection` instance.

At the moment, `Collection.filter()` returns `Array` and `NamedCollection.filter()` returns plain `Object`.

To retrieve `Array` or `Object`, a corresponding methods `Collection.toArray()` and `NamedCollection.toObject()` should be created, like https://api.jquery.com/toArray/.

**Comment by Reinmar** [comment]
I was considering this, but in my opinion it will be rather unnecessary complication.

* We need to know the exact constructor of the current collection (it may be a child constructor). Note that it might need some additional arguments. AFAIK, that won't be doable in some cases.
* In many use cases you will be interested in getting an array, not a collection. Of course you may then use `toArray()` but that means two additional steps (creating a collection with all its internals and casting it back to array) so it's a performance loss.

So I'd rather keep what we have now and if needed add the ability to create a collection out of an array/object. That would give you the same possibilities:

```
var filteredCollection = new Collection( collection.filter( giveMeOdds ) );
```

**Comment by scofalik** [comment]
I support Olek. Current solution brings ambiguity. In this case I rather have *good solution than the better one*.

* I don't know if I understand you correctly. But if inheritance is a case, child class should overload `filter` method too (if constructor differs). Will that solve the issue?
* Creating `Collection` from an array is not that complex so there is not much loss unless you do it in a long loop. We may even skip firing event(s) if `Collection` is initialized using an array/object so the only performance loss will be connected with creating an object. Nothing more will happen.

**Comment by Reinmar** [comment]
> I don't know if I understand you correctly. But if inheritance is a case, child class should overload filter method too (if constructor differs). Will that solve the issue?

In such case every time you inherit from `Collection` you need to override all `forEach/filter/etc` methods. That's not fun.

To clarify – you always have `this.constructor`, but you don't know (AFAIK) its arguments.

> Creating Collection from an array is not that complex so there is not much loss unless you do it in a long loop. We may even skip firing event(s) if Collection is initialized using an array/object so the only performance loss will be connected with creating an object. Nothing more will happen.

But still these 2 steps are unnecessary if you are not interested in getting a collection. That's the point. 

----

In a F2F discussion with @scofalik I said that I found the current solution the best choice because you don't want to create filtered/mapped collections of some objects. For instance we've got `PluginCollection` which inherits from `NamedCollection`, but I can't think of a use case when you'd like to have another one as this would be very ambiguous how does `PluginCollection.load()` behaves in the new collection.

That lead us to thinking whether it's semantically correct that `PluginCollection` inherits from `NamedCollection` and TBH it's both useful and semantically incorrect as the derived class can't be used in the same way as the parent class (you can only `load()` plugins, but you can't `add()` them). I'm not sure what's the perfect design of this, but we noticed that splitting the plugin loader from the plugin collection would actually require from us blocking the `collection.add()` method anyway so that doesn't simplify anything. Therefore, I'm rather for blocking `add()` on the current version of `PluginCollection`.

Second thing that we noticed is that when we merge `Collection` and `NamedCollection` as described in #58, then it won't be that clear if the `filter()` method should return an array or an object. IMO it should still return an array, as the names are kept inside the items anyway. But it really depends on the use cases that we'll find whether this design is OK.

---

**Anyway, the most important fact is that so far none of us mentioned any real problems with the current solution, so my proposal is to postpone this discussion until we have something concrete to work on.**

**Comment by pjasiun** [comment]
I do not get why `Collection` and `NamedCollection` have methods like `forEach/filter/etc`. They should implement `Symbol.iterator` interface and filtering should works on that iterator, not on the collection itself.

**Comment by Reinmar** [comment]
> I do not get why Collection and NamedCollection have methods like forEach/filter/etc. They should implement Symbol.iterator interface and filtering should works on that iterator, not on the collection itself.

+1.

The only problem is that [lodash does not support](https://github.com/lodash/lodash/issues/737) iterators yet. So if you want to filter one iteratable object you need to write this:

```
function* higher( iterator ) {
    for( i of iterator ) {
        if( i > 100 ) {
            yield i;
        }
    }
}

for( h of higher( collection ) ) {
    // do something with a filtered collection...
}
```

Instead of doing this (works now):

```
for ( h of collection.filter( i => i > 100 ) ) {
    // do something with a filtered collection...
}
```

If lodash supported iterables, then we could do something like:

```
for ( h of _.filter( collection, i => i > 100 ) ) {
    ...
}
```

So for now we can do two things:

* Agree to define a filtering generator every time you want to filter some collection (the first code sample) and wait for ES2016+ to define syntax sugar for filtering iterables.
* Create our simple `utils.filterIterable()`, `utils.findInIterable()`, etc methods.

**Comment by pjasiun** [comment]
And then, one day we will be able to copres it using [Generator comprehensions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Generator_comprehensions#Differences_to_the_older_JS1.7.2FJS1.8_comprehensions):
```
for( h of ( ( for c of collection ) if (c > 100) c) ) ) {
    // do something with a filtered collection...
}
```
Maybe ;)

**Comment by oleq** [comment]
> Anyway, the most important fact is that so far none of us mentioned any real problems with the current solution, so my proposal is to postpone this discussion until we have something concrete to work on.

The point is that such basic classes will be reused hundreds of times and, eventually, there will be no way back out of this mess if we find out that my proposal was correct. So it's more like now–or–never situation.

> The only problem is that lodash does not support iterators yet. So if you want to filter one iteratable object you need to write this

This is why I wanted to leave the `toArray` interface available for lodash or whatever data processor that works with native data types.

---

But anyway, with the following definition of `Symbol.iterator` in `Collection` class

```
class Collection {
    ...
    [Symbol.iterator]() {
        let i = 0;

        return {
            next: () => {
                return {
                    done: !( i in this._models ),
                    value: this._models[ i++ ]
                };
            }
        };
    }
    ...
}
```

this works perfectly

```
var c = new Collection();

c.add( 'foo' );
c.add( 42 );
c.add( [ 'bar' ] );

for ( let i of c.filter( isNaN ) ) {
    console.log( i );
}

> foo
> ["bar"]
```

as long as `Collection.filter()` returns an instance of `Collection`. Tested in Chrome.

**Comment by pjasiun** [comment]
Note that you can use:
```
class Collection {
	// ...
	[ Symbol.iterator ]() {
		return this._models[ Symbol.iterator ]();
	}
	// ...
}
```

**Comment by pjasiun** [comment]
> as long as Collection.filter() returns an instance of Collection. Tested in Chrome.

This will work whenever `Collection.filter()` returns iterable. If the only possible action on the filtered data will be to iterate over it, can't we say that `filter` returns `iteratable of models`? They we can implement it with array, or collection, or set, or whatever we find the best.

Of course we can not prevent users to use other, implementation specific, methods, but users always may use our code different way that we documented it.

Digression: I realized that it almost always makes sens to said that acceptable parameter is any Iterable instead of an array (see: https://github.com/cksource/ckeditor5-core/blob/d960740/src/document/node.js#L22)

**Comment by oleq** [comment]
```
class Collection {
    // ...
    [ Symbol.iterator ]() {
        return this._models[ Symbol.iterator ]();
    }
    // ...
}
```

@pjasiun :+1: But still we need to use a custom iterator for `NamedCollection` because it uses native objects.

So what's your final opinion about the proposed change?

**Comment by Reinmar** [comment]
In #77 a collection iterator will be introduced.

**Comment by oleq** [comment]
Can we mark the issue as fixed?
