### ISSUE TITLE
Does the Position have to be based on path instead of container and offset?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#83]
While writing https://github.com/ckeditor/ckeditor5-core/issues/65#issuecomment-155754045 I also started doubting whether the `Position` class make any sense in its current form. I may not see the whole picture, but basing it on path was a strange decision in my opinion. Could you explain @pjasiun why it works this way?

You can also try to answer the question why not using the same interface which the native DOM has with its `Range`, `TreeWalker/NodeIterator` etc?

**Comment by pjasiun** [comment]
Because of OT position should have a valid information without a document. We need to be able to get the information that one node is a descendant of another node or that one positions is inside the range. Note that document may be totally different at the moment of transforming operations, so operations need to keep all the information needed to transform. This include the fact that positions should be document independent.

**Comment by Reinmar** [comment]
I think I get it, but could you give more "verbose" examples (mainly, for the future reference).

**Comment by pjasiun** [comment]
In the collaborative editing client needs to transform operations from the server, but he already changed the document, so the document state is different than operations base document version. Another case: during the selective undo, we need to create a revers operation from the historical operation, but we also do not have the state of the document at that historical point.

Because of these reasons the rule is simple: we need to be able to create a reverse operation or transform one operation by another having only these operation, without the document data (nodes structure).

The position as a path give us much more information in that case then position as a node + offset. For example we know that [ 1, 2, 4 ] i the position in the parent of [ 1, 2, 3, 5, 6 ]. We also know that if one operation removes 5 nodes starting from [ 1, 2, 0 ] and another insert something into [ 1, 2, 3, 5, 6 ] the second operation needs to be changed and insert the content into the detached tree. Also we know that, if one operation is adding style on the range from [ 1 ] to [ 3, 5 ] and the second is insert at [ 2, 1, 0 ], then the insertion inside the changed range needs to split the change operation.

We would not be able to do any of these having node + offset, because we can not get a parent of that node (node can be in the totally different place at the moment of transforming then it was at the moment of applying operation).

Is it cleaner now?
